### PR TITLE
Add pip setup.py

### PR DESCRIPTION
**Pull request by oschwengers**
Hello @savojard , thanks a lot for developing & maintaining this very nice signal peptide detection tool!

In order to to include it into some larger pipelines I'd like to create a conda package to streamline the installation procedure and its distribution (#15). However, as there is no `setup.py` which is recommended as best practices for Python tools, the conda package creation is somewhat difficult (https://github.com/bioconda/bioconda-recipes/pull/7486).

Hence, I've refactored the Python source code into a `deepsig` package and added a `setup.py`. A local installation via pip was successful. If this PR could be accepted I'd try to create a Conda package and upload it to Bioconda.

Of course, this PR would surely benefit from more testing. I'm lokking forward to your thoughts.
Best regard!

### CODE REVIEW

**Comment by savojard** [comment]
Hello @oschwengers, thanks for the PR. I'm very happy to have deeps on Bioconda. I'm not very familiar with that and so your help is really appreciated!

However,  I've tested your PR and the program did not work. The problem stands on the fact that deepsig needs the ENV variable DEEPSIG_ROOT to be set and point to the program root directory.

If you could fix this I'll be very happy to merge your PR and proceed to Bioconda upload.
Thanks!
Best regards

**Comment by oschwengers** [comment]
Hi @savojard , I'm glad that your open to this PR.
I've added 3 more commits:
- fixing a wrong author email
- adding a `.gitignore`
- adding a runtime check for the `DEEPSIG_ROOT` env var

Currently, after installing DeepSig via Pip, the user is required to set the environment variable manually.

My idea is, that after having accepted this PR and uploading it to PyPI (by you as the original author), I will then create an PR to Bioconda in order to create a new DeepSig package.
Within this package, the `DEEPSIG_ROOT` env var will be automatically set by Conda.
Would that be OK for you? Of course, the readme still needs some adoptions to the new setup routine. I thought that this could  maybe be done by you ?
Thanks and best regards!

**Comment by savojard** [comment]
For sure I can change the README. 
Concerning the new setup there is also another issue: DeepSig depends on some pre-trained model stored in the "models" folder and an external tool written by me and stored in "tools" folder. Setting the DEEPSIG_ROOT allows the program to find these data.
Should we include them in the setup? 
(sorry if I'm not answering quickly but in these days I'm very busy)

**Comment by oschwengers** [comment]
I've seen these data/executable - unfortunately, I don't know of an easy / straight forward way to setup this via the `setup.py`.
Therefore, I've moved the responsibility to user to set the `DEEPSIG_ROOT` env var manually to the root dir which must be downloaded, e.g. via `git clone...`.
For pip, this is rather inconvenient but as I said, once we have this in Pip I'll try to create a conda package which will take care of this automatically.

**Pull request merged**
